### PR TITLE
composer: allow installing Symfony 3 components

### PR DESCRIPTION
**Pull request by TomasVotruba**
Without this it's impossible to use DoctrineBundle with Symfony 3 components.

### CODE REVIEW

**Comment by xabbuh** [comment]
Imho you should then add a Travis job that explicitly requires the 3.0 versions to make sure that the bundle really is compatible with the new major version.

**Comment by TomasVotruba** [comment]
@xabbuh Good point. Do you have any existing example of that?

**Comment by xabbuh** [comment]
@TomasVotruba You could take a look at how the [FOSRestBundle](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/.travis.yml) does it, for example (it doesn't test 3.0 actually, but imho the conecpt should become clear).

**Comment by TomasVotruba** [comment]
Not relevant for me anymore.

**Pull request closed without merging**
