### PR TITLE
Fix #111 mocking kernel methods

### LINKED ISSUE #111: Test failures with latest symfony (2.8.21, 2.3.0)
Found in Fedora QA after update from 2.8.20 to 2.8.21 (everything was ok with previous version)
https://apps.fedoraproject.org/koschei/package/php-doctrine-doctrine-cache-bundle?collection=f27

Reproduced using git + composer (so with symfony 2.3.0)
```
$ vendor/bin/phpunit --verbose
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.19
Configuration:	/tmp/DoctrineCacheBundle/phpunit.xml.dist

............................................EEEEEE.SSSS.....S..

Time: 230 ms, Memory: 16.00MB

There were 6 errors:

1) Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Command\ContainsCommandTest::testContainsFalse
Invalid argument supplied for foreach()

/tmp/DoctrineCacheBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:141
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:124
/tmp/DoctrineCacheBundle/vendor/symfony/console/Application.php:90
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:43
/tmp/DoctrineCacheBundle/Tests/Functional/Command/CommandTestCase.php:53
/tmp/DoctrineCacheBundle/Tests/Functional/Command/ContainsCommandTest.php:30

2) Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Command\ContainsCommandTest::testContainsTrue
Invalid argument supplied for foreach()

/tmp/DoctrineCacheBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:141
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:124
/tmp/DoctrineCacheBundle/vendor/symfony/console/Application.php:90
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:43
/tmp/DoctrineCacheBundle/Tests/Functional/Command/CommandTestCase.php:53
/tmp/DoctrineCacheBundle/Tests/Functional/Command/ContainsCommandTest.php:30

3) Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Command\DeleteCommandTest::testDeleteSuccess
Invalid argument supplied for foreach()

/tmp/DoctrineCacheBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:141
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:124
/tmp/DoctrineCacheBundle/vendor/symfony/console/Application.php:90
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:43
/tmp/DoctrineCacheBundle/Tests/Functional/Command/CommandTestCase.php:53
/tmp/DoctrineCacheBundle/Tests/Functional/Command/DeleteCommandTest.php:30

4) Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Command\DeleteCommandTest::testDeleteAll
Invalid argument supplied for foreach()

/tmp/DoctrineCacheBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:141
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:124
/tmp/DoctrineCacheBundle/vendor/symfony/console/Application.php:90
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:43
/tmp/DoctrineCacheBundle/Tests/Functional/Command/CommandTestCase.php:53
/tmp/DoctrineCacheBundle/Tests/Functional/Command/DeleteCommandTest.php:30

5) Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Command\FlushCommandTest::testFlush
Invalid argument supplied for foreach()

/tmp/DoctrineCacheBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:141
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:124
/tmp/DoctrineCacheBundle/vendor/symfony/console/Application.php:90
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:43
/tmp/DoctrineCacheBundle/Tests/Functional/Command/CommandTestCase.php:53
/tmp/DoctrineCacheBundle/Tests/Functional/Command/FlushCommandTest.php:30

6) Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Command\StatsCommandTest::testStats
Invalid argument supplied for foreach()

/tmp/DoctrineCacheBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:141
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:124
/tmp/DoctrineCacheBundle/vendor/symfony/console/Application.php:90
/tmp/DoctrineCacheBundle/vendor/symfony/framework-bundle/Console/Application.php:43
/tmp/DoctrineCacheBundle/Tests/Functional/Command/CommandTestCase.php:53
/tmp/DoctrineCacheBundle/Tests/Functional/Command/StatsCommandTest.php:30

```

### PR DESCRIPTION
**Pull request by remicollet**
Perhaps not the simplest way.. btw, seems to work...

### CODE REVIEW

**Comment by xabbuh** [comment]
`return $this->getMock('Symfony\Component\HttpKernel\KernelInterface');` does not work?

**Comment by remicollet** [comment]
@xabbuh no

**Comment by stof** [comment]
@xabbut see https://github.com/doctrine/DoctrineCacheBundle/issues/111. the issue is that creating a mock returning `null` for all methods is broken, as `getBundles` must return an iterable for instance

**Comment by alcaeus** [comment]
Thanks @remicollet!

**Pull request merged**
