### PR TITLE
Add connection timeout parameter for Redis

### PR DESCRIPTION
**Pull request by martinfobian**

### CODE REVIEW

**Comment by xabbuh** [comment]
The XML schema file should be updated as well so that one is able to use the config option in XML files too.

**Comment by martinfobian** [comment]
Are you referring to the doctrine_cache-1.0.xsd file? Since only "host" and "port" are in there, I figured optional parameters (like database, password) wouldn't have to go in there.

**Comment by xabbuh** [comment]
@martinfobian Yes, if other options are not present, they would need to be added too.

**Comment by yamek** [comment]
You can merge my [pull request](https://github.com/doctrine/DoctrineCacheBundle/pull/61) to add the missing XML configuration settings. I've just seen your pull request. Simply add the timeout option on the xsd file (I missed that one ;) )

**Pull request closed without merging**
