### PR TITLE
Set provider services public

### PR DESCRIPTION
**Pull request by magnetik**
Hi,

I'm not sure that this is wanted, but it makes the test pass "more".

Relates to #101

### CODE REVIEW

**Comment by magnetik** [comment]
About the failing test, they fail for master too.
This PR fix ~15 "service or alias has been removed or inlined when the container was compiled" errors in the test.

**Comment by Majkl578** [comment]
Failures due ResolveDefinitionTemplatesPass not present in SF 4.

**Comment by stof** [comment]
this compiler pass has been renamed in 3.4 (keeping the old name around for BC). You should check for the existence of the new class and use it instead.

**Comment by magnetik** [comment]
Okay I'll prepare another PR for this.

**Comment by magnetik** [comment]
see #134

**Comment by magnetik** [comment]
Closed for #135 that contains all fixes for SF4 compatibility

**Pull request closed without merging**
