### PR TITLE
Fix composer.json compat with symfony/security-acl <2.7

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fixes https://github.com/doctrine/DoctrineBundle/issues/481

### CODE REVIEW

**Comment by xabbuh** [comment]
This won't work too. There is no `2.3` release of the ACL package (as long as we don't add a `provide` entry in Symfony).

**Comment by stof** [comment]
@xabbuh the replace rule has been added in Symfony 2.3 already, to avoid issues as Symfony 2.3 contains the code for the acl subsystem: https://github.com/symfony/symfony/blob/2.3/composer.json#L51

**Comment by stof** [comment]
it is not yet released though, but I hope we will have a new release soon

**Comment by xabbuh** [comment]
Oh indeed, I forgot that this was merged after the last release when I tested this.

**Pull request merged**
