### PR TITLE
Allow Symfony 5.0

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Until this is completely removed from DoctrineBundle, let's allow the Symfony 5.0 CI to pass.
Sibling of https://github.com/doctrine/DoctrineBundle/pull/975

### CODE REVIEW

**Comment by alcaeus** [comment]
Merging this PR until we have removed the dependency on this bundle from DoctrineBundle. The decision to deprecate this bundle and not add support for Symfony 5 (as indicated in #156) still stands: this PR will be reverted once we've removed the dependency mentioned above.

**Comment by mvorisek** [comment]
Can a new tagged release be made to reflect this merged PR?

**Comment by alcaeus** [comment]
No:

> Merging this PR until we have removed the dependency on this bundle from DoctrineBundle. The decision to deprecate this bundle and not add support for Symfony 5 (as indicated in #156) still stands: this PR will be reverted once we've removed the dependency mentioned above.

See also https://github.com/doctrine/DoctrineCacheBundle/pull/161.

**Comment by stof** [comment]
Well, we should tag a release, otherwise DoctrineBundle cannot be installed in a Symfony 5 project without people adding a root requirement on DoctrineCacheBundle to whitelist its dev version, which will actually make the deprecation harder.
That's either that, or removing the dependency in DoctrineBundle must be given a very high priority.

**Comment by alcaeus** [comment]
> That's either that, or removing the dependency in DoctrineBundle must be given a very high priority.

The dependency has been removed as of the 2.0 release: https://github.com/doctrine/DoctrineBundle/pull/1029

**Comment by stof** [comment]
Oh, I forgot that. Then it is fine.

**Pull request merged**
