### PR TITLE
Improved support of Symfony 3.4/4.0

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by alcaeus** [comment]
This isn't necessary: the command name is set in the commands' `configure` method which also makes it usable outside the DI container. Closing as `invalid`.

**Comment by mickaelandrieu** [comment]
It's not invalid, it's the expected behavior in Symfony 3.4 (https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php#L52). More, using something else than the bin/console of Symfony framework - let's say some editor's command like Drupal or PrestaShop's one - make the command unavailable.

Still, I accept your decision :+1:

**Comment by stof** [comment]
setting it in the tag name allows Symfony to lazy-load the command (as it does not need to instantiate it to know the name to be registered)

**Comment by alcaeus** [comment]
@stof lazy-loading is nice, but in this case it requires the command name to be duplicated. After all, the `console.command` DI tag is only one way to add the command to a CLI application.

@mickaelandrieu not sure I understand: how is it better to only set the command name in the DI container instead of in the commands' `configure` method? How does doing that in the `configure` method (which is invoked in the constructor of the command) break using the Drupal or PrestaShop command app?

**Comment by mickaelandrieu** [comment]
@alcaeus I don't think using reflection to guess the name of the command is the expected behavior, except if I'm wrong the command name set in `configure` function is not used to retrieve the command name, but only when displaying the console.

In PrestaShop, we have a special class to execute some commands and for some reasons the compiler pass is unable to retrieve the `getDefaultName` from `Command` parent class. My guess here is it's because of autoloading/DI improvements added in 3.4.

To be precise, autoloading of Doctrine commands without using `bin/console` is broken.

It's totally an edge case and you don't have to manage it.

Now let's consider again my contribution: this add litteraly no maintenance for the bundle, but it will allow lazy loading and use of theses commands in every Container Aware Console applications. So for you, no pain and for me (as part of PrestaShop team) very very very very very .... helpful.

To end with it, I think duplicate the name is worth because the command name won't change without a really really good reason.

Thanks for reading, and again, I accept your decision :) Have a nice week end @alcaeus !

**Pull request closed without merging**
